on: 
  workflow_dispatch:
  
name: Notify Harry
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v2
#     - name: Slack Notification
#       uses: rtCamp/action-slack-notify@v2
#       env:
#         SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#         SLACK_ICON: https://github.com/rtCamp.png?size=48
#         SLACK_MESSAGE: 'Post Content Harry :rocket:'
#         SLACK_TITLE: Post Title
#         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
    - name: Slack Notification Demo
      uses: bryannice/gitactions-slack-notification@2.0.0
      env:
        SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Demo''ing the Slack Notification'
        SLACK_TITLE: 'Slack Notification Demo'
