on: 
  workflow_dispatch:
  
name: Notify Harry
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
#     - name: Slack Notification Demo
#       uses: bryannice/gitactions-slack-notification@2.0.0
#       env:
#         SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#         SLACK_MESSAGE: 'mWeb24x7 job is failed. Please run manually :rocket:'
#         SLACK_TITLE: 'mWeb24x7 Job failed'
#         SLACK_USERNAME: mWeb24x7
#         SLACK_COLOR: danger
#         SLACK_ICON: 'https://github.com/rtCamp.png?size=48'

    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
#         status: ${{ job.status }}
        status: failure
        author_name: 'mWeb24x7'
        fields: repo,message,eventName,workflow # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
        AS_MESSAGE: "Job failed Please check and rerun again."
      if: always() # Pick up events even if the job fails or is canceled.
      
      # Check Website Status
    - name: Check Server location
      run: |
        echo "${SLACK_WEBHOOK_URL}" > test.txt
        cat test.txt
        curl -Ls http://ip-api.com?fields=message,country,regionName,city,timezone,isp,query 
